// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using News_Back_end;

#nullable disable

namespace News_Back_end.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BroadcastMessagePublicationDraft", b =>
                {
                    b.Property<int>("BroadcastMessagesId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedArticlesPublicationDraftId")
                        .HasColumnType("int");

                    b.HasKey("BroadcastMessagesId", "SelectedArticlesPublicationDraftId");

                    b.HasIndex("SelectedArticlesPublicationDraftId");

                    b.ToTable("BroadcastMessageArticles", (string)null);
                });

            modelBuilder.Entity("IndustryTagMember", b =>
                {
                    b.Property<int>("IndustryTagsIndustryTagId")
                        .HasColumnType("int");

                    b.Property<int>("MembersMemberId")
                        .HasColumnType("int");

                    b.HasKey("IndustryTagsIndustryTagId", "MembersMemberId");

                    b.HasIndex("MembersMemberId");

                    b.ToTable("MemberIndustryTags", (string)null);
                });

            modelBuilder.Entity("InterestTagMember", b =>
                {
                    b.Property<int>("InterestsInterestTagId")
                        .HasColumnType("int");

                    b.Property<int>("MembersMemberId")
                        .HasColumnType("int");

                    b.HasKey("InterestsInterestTagId", "MembersMemberId");

                    b.HasIndex("MembersMemberId");

                    b.ToTable("MemberInterests", (string)null);
                });

            modelBuilder.Entity("InterestTagPublicationDraft", b =>
                {
                    b.Property<int>("InterestTagsInterestTagId")
                        .HasColumnType("int");

                    b.Property<int>("PublicationDraftsPublicationDraftId")
                        .HasColumnType("int");

                    b.HasKey("InterestTagsInterestTagId", "PublicationDraftsPublicationDraftId");

                    b.HasIndex("PublicationDraftsPublicationDraftId");

                    b.ToTable("PublicationDraftInterestTags", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSelectedTopics")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Lastlogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.BroadcastAnalyticsSummary", b =>
                {
                    b.Property<int>("BroadcastAnalyticsSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BroadcastAnalyticsSummaryId"));

                    b.Property<int>("BroadcastMessageId")
                        .HasColumnType("int");

                    b.Property<double>("ClickRate")
                        .HasColumnType("float");

                    b.Property<double>("ClickToOpenRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DeliveryRate")
                        .HasColumnType("float");

                    b.Property<int>("DesktopOpens")
                        .HasColumnType("int");

                    b.Property<string>("EngagementByCountryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngagementByIndustryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngagementByInterestJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngagementByLanguageJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstOpenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastOpenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MobileOpens")
                        .HasColumnType("int");

                    b.Property<double>("OpenRate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PeakEngagementHour")
                        .HasColumnType("datetime2");

                    b.Property<int>("TabletOpens")
                        .HasColumnType("int");

                    b.Property<int>("TotalBounced")
                        .HasColumnType("int");

                    b.Property<int>("TotalClicks")
                        .HasColumnType("int");

                    b.Property<int>("TotalDelivered")
                        .HasColumnType("int");

                    b.Property<int>("TotalOpens")
                        .HasColumnType("int");

                    b.Property<int>("TotalSent")
                        .HasColumnType("int");

                    b.Property<int>("UniqueClicks")
                        .HasColumnType("int");

                    b.Property<int>("UniqueOpens")
                        .HasColumnType("int");

                    b.HasKey("BroadcastAnalyticsSummaryId");

                    b.HasIndex("BroadcastMessageId")
                        .IsUnique();

                    b.ToTable("BroadcastAnalyticsSummaries");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.BroadcastDelivery", b =>
                {
                    b.Property<int>("BroadcastDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BroadcastDeliveryId"));

                    b.Property<string>("BounceReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BounceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BroadcastMessageId")
                        .HasColumnType("int");

                    b.Property<int>("ClickCount")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeliverySuccess")
                        .HasColumnType("bit");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailClient")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailOpened")
                        .HasColumnType("bit");

                    b.Property<int?>("EstimatedReadTimeSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstClickedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstOpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasClicked")
                        .HasColumnType("bit");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastClickedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastOpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("OpenCount")
                        .HasColumnType("int");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Unsubscribed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UnsubscribedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BroadcastDeliveryId");

                    b.HasIndex("MemberId");

                    b.HasIndex("BroadcastMessageId", "MemberId")
                        .IsUnique();

                    b.ToTable("BroadcastDeliveries");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.BroadcastLinkClick", b =>
                {
                    b.Property<int>("BroadcastLinkClickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BroadcastLinkClickId"));

                    b.Property<int>("BroadcastDeliveryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClickedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailClient")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PublicationDraftId")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BroadcastLinkClickId");

                    b.HasIndex("BroadcastDeliveryId");

                    b.HasIndex("PublicationDraftId");

                    b.ToTable("BroadcastLinkClicks");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.BroadcastMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ScheduledSendAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetAudience")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("BroadcastMessages");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.ConsultantInsightsSendLog", b =>
                {
                    b.Property<int>("ConsultantInsightsSendLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultantInsightsSendLogId"));

                    b.Property<string>("ConsultantUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PeriodDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("ConsultantInsightsSendLogId");

                    b.HasIndex("ConsultantUserId", "Period", "PeriodDateUtc")
                        .IsUnique();

                    b.ToTable("ConsultantInsightsSendLogs");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.ConsultantPreference", b =>
                {
                    b.Property<int>("ConsultantPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultantPreferenceId"));

                    b.Property<string>("ConsultantUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IndustriesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreferredTimeMinutesUtc")
                        .HasColumnType("int");

                    b.Property<string>("TerritoriesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ConsultantPreferenceId");

                    b.HasIndex("ConsultantUserId")
                        .IsUnique();

                    b.ToTable("ConsultantPreferences");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.DailyBroadcastMetric", b =>
                {
                    b.Property<int>("DailyBroadcastMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyBroadcastMetricId"));

                    b.Property<double>("AverageClickRate")
                        .HasColumnType("float");

                    b.Property<double>("AverageOpenRate")
                        .HasColumnType("float");

                    b.Property<int>("BroadcastsSent")
                        .HasColumnType("int");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MetricDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewSubscribersEngaged")
                        .HasColumnType("int");

                    b.Property<int>("TotalClicks")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmailsDelivered")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmailsSent")
                        .HasColumnType("int");

                    b.Property<int>("TotalOpens")
                        .HasColumnType("int");

                    b.Property<int>("UniqueRecipientsReached")
                        .HasColumnType("int");

                    b.HasKey("DailyBroadcastMetricId");

                    b.HasIndex("MetricDate")
                        .IsUnique();

                    b.ToTable("DailyBroadcastMetrics");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.FetchMetric", b =>
                {
                    b.Property<int>("FetchMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FetchMetricId"));

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemsFetched")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("FetchMetricId");

                    b.ToTable("FetchMetrics");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.IndustryTag", b =>
                {
                    b.Property<int>("IndustryTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryTagId"));

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionZH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameZH")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IndustryTagId");

                    b.ToTable("IndustryTags");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.InterestTag", b =>
                {
                    b.Property<int>("InterestTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestTagId"));

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionZH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameZH")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InterestTagId");

                    b.ToTable("InterestTags");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ApplyToAllTopics")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NotificationChannels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredChannel")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MemberId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.MemberEngagementProfile", b =>
                {
                    b.Property<int>("MemberEngagementProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberEngagementProfileId"));

                    b.Property<string>("EngagementLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("FrequencyScore")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastEmailOpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastEmailReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLinkClickedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("LifetimeClickRate")
                        .HasColumnType("float");

                    b.Property<double>("LifetimeOpenRate")
                        .HasColumnType("float");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<double>("OverallEngagementScore")
                        .HasColumnType("float");

                    b.Property<int?>("PreferredDayOfWeek")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredHourOfDay")
                        .HasColumnType("int");

                    b.Property<double>("RecencyScore")
                        .HasColumnType("float");

                    b.Property<string>("TopEngagedTopicsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalEmailsOpened")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmailsReceived")
                        .HasColumnType("int");

                    b.Property<int>("TotalLinksClicked")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberEngagementProfileId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("MemberEngagementProfiles");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.NewsArticle", b =>
                {
                    b.Property<int>("NewsArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsArticleId"));

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DescriptionSettingId")
                        .HasColumnType("int");

                    b.Property<string>("FullContentEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullContentZH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NLPKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamedEntities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SentimentScore")
                        .HasColumnType("float");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("SourceURL")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SummaryEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryZH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEN")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TranslatedContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslationLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("TranslationReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TranslationReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TranslationSavedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TranslationSavedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("NewsArticleId");

                    b.HasIndex("SourceId");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.PublicationDraft", b =>
                {
                    b.Property<int>("PublicationDraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublicationDraftId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullContentEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullContentZH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImageAlt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HeroImageSource")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("IndustryTagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("NewsArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PublicationDraftId");

                    b.HasIndex("IndustryTagId");

                    b.HasIndex("NewsArticleId");

                    b.ToTable("PublicationDrafts");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceId"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CrawlFrequency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastCrawledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Ownership")
                        .HasColumnType("int");

                    b.Property<int>("RegionLevel")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("SourceId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.SourceDescriptionSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomKeyPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HighlightEntities")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeChineseSummary")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeEnglishSummary")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeOriginalChinese")
                        .HasColumnType("bit");

                    b.Property<int>("MaxArticlesPerFetch")
                        .HasColumnType("int");

                    b.Property<int>("MinArticleLength")
                        .HasColumnType("int");

                    b.Property<bool>("SentimentAnalysisEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("SummaryFocus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryTone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SummaryWordCount")
                        .HasColumnType("int");

                    b.Property<bool>("TranslateOnFetch")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingId");

                    b.HasIndex("SourceId");

                    b.ToTable("SourceDescriptionSettings");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.TopicPerformanceMetric", b =>
                {
                    b.Property<int>("TopicPerformanceMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicPerformanceMetricId"));

                    b.Property<double>("AverageClickRate")
                        .HasColumnType("float");

                    b.Property<double>("AverageOpenRate")
                        .HasColumnType("float");

                    b.Property<int>("BroadcastCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("EngagementScore")
                        .HasColumnType("float");

                    b.Property<int?>("IndustryTagId")
                        .HasColumnType("int");

                    b.Property<int?>("InterestTagId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MetricDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalClicks")
                        .HasColumnType("int");

                    b.Property<int>("TotalOpens")
                        .HasColumnType("int");

                    b.Property<int>("TotalSent")
                        .HasColumnType("int");

                    b.HasKey("TopicPerformanceMetricId");

                    b.HasIndex("IndustryTagId");

                    b.HasIndex("InterestTagId");

                    b.HasIndex("MetricDate", "InterestTagId", "IndustryTagId");

                    b.ToTable("TopicPerformanceMetrics");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.TranslationAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewsArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TranslationAudits");
                });

            modelBuilder.Entity("BroadcastMessagePublicationDraft", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.BroadcastMessage", null)
                        .WithMany()
                        .HasForeignKey("BroadcastMessagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News_Back_end.Models.SQLServer.PublicationDraft", null)
                        .WithMany()
                        .HasForeignKey("SelectedArticlesPublicationDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IndustryTagMember", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.IndustryTag", null)
                        .WithMany()
                        .HasForeignKey("IndustryTagsIndustryTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News_Back_end.Models.SQLServer.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterestTagMember", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.InterestTag", null)
                        .WithMany()
                        .HasForeignKey("InterestsInterestTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News_Back_end.Models.SQLServer.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterestTagPublicationDraft", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.InterestTag", null)
                        .WithMany()
                        .HasForeignKey("InterestTagsInterestTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News_Back_end.Models.SQLServer.PublicationDraft", null)
                        .WithMany()
                        .HasForeignKey("PublicationDraftsPublicationDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News_Back_end.Models.SQLServer.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.BroadcastAnalyticsSummary", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.BroadcastMessage", "BroadcastMessage")
                        .WithMany()
                        .HasForeignKey("BroadcastMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BroadcastMessage");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.BroadcastDelivery", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.BroadcastMessage", "BroadcastMessage")
                        .WithMany()
                        .HasForeignKey("BroadcastMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News_Back_end.Models.SQLServer.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BroadcastMessage");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.BroadcastLinkClick", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.BroadcastDelivery", "BroadcastDelivery")
                        .WithMany("LinkClicks")
                        .HasForeignKey("BroadcastDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News_Back_end.Models.SQLServer.PublicationDraft", "PublicationDraft")
                        .WithMany()
                        .HasForeignKey("PublicationDraftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BroadcastDelivery");

                    b.Navigation("PublicationDraft");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.ConsultantInsightsSendLog", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.ApplicationUser", "ConsultantUser")
                        .WithMany()
                        .HasForeignKey("ConsultantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultantUser");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.ConsultantPreference", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.ApplicationUser", "ConsultantUser")
                        .WithMany()
                        .HasForeignKey("ConsultantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultantUser");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.Member", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.ApplicationUser", "ApplicationUser")
                        .WithOne("Member")
                        .HasForeignKey("News_Back_end.Models.SQLServer.Member", "ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.MemberEngagementProfile", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.NewsArticle", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.PublicationDraft", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.IndustryTag", "IndustryTag")
                        .WithMany("PublicationDrafts")
                        .HasForeignKey("IndustryTagId");

                    b.HasOne("News_Back_end.Models.SQLServer.NewsArticle", "NewsArticle")
                        .WithMany()
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndustryTag");

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.SourceDescriptionSetting", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.TopicPerformanceMetric", b =>
                {
                    b.HasOne("News_Back_end.Models.SQLServer.IndustryTag", "IndustryTag")
                        .WithMany()
                        .HasForeignKey("IndustryTagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("News_Back_end.Models.SQLServer.InterestTag", "InterestTag")
                        .WithMany()
                        .HasForeignKey("InterestTagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IndustryTag");

                    b.Navigation("InterestTag");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.ApplicationUser", b =>
                {
                    b.Navigation("Member");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.BroadcastDelivery", b =>
                {
                    b.Navigation("LinkClicks");
                });

            modelBuilder.Entity("News_Back_end.Models.SQLServer.IndustryTag", b =>
                {
                    b.Navigation("PublicationDrafts");
                });
#pragma warning restore 612, 618
        }
    }
}
